version: '3.8'

services:
  db_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db_sqlserver
    environment:
      SA_PASSWORD: "docker@sql01"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - local-docker-network

networks:
  local-docker-network:
    name: local-docker-network
    driver: bridge